# Generated by scripts/release.sh in ronalove/recruit: change the script, not this file.
class Recruit < Formula
  desc "Launch a team of Claude Code agents, each one knowing its role and its teammates"
  homepage "https://github.com/ronalove/recruit"
  license "AGPL-3.0-or-later"

  head do
    url "https://github.com/ronalove/recruit.git", branch: "main"
    depends_on "rust" => :build
  end

  on_macos do
    on_arm do
      url "https://github.com/ronalove/recruit/releases/download/v2.0.0/recruit-2.0.0-aarch64-apple-darwin.tar.gz"
      sha256 "e6cd3b1fab9d0d8dac1ac1f3452880a1cd275ce7647453f3cd61c0f505dff8b4"
    end
    on_intel do
      url "https://github.com/ronalove/recruit/releases/download/v2.0.0/recruit-2.0.0-x86_64-apple-darwin.tar.gz"
      sha256 "abf01480faa1cec1c70e72a3cb0f2e9d00f7fd25f8ce63b7f0e85c375e4ed529"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ronalove/recruit/releases/download/v2.0.0/recruit-2.0.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "f8ad5cb817ace32b868e8759e2129fe279baf8e955b92090af9d2da2fdd0ecab"
    end
    on_intel do
      url "https://github.com/ronalove/recruit/releases/download/v2.0.0/recruit-2.0.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "bb5de1df384edf14bfe1992dc36242acc703cb2704d91e16215e8876e8b8850f"
    end
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      bin.install "recruit"
    end
  end

  def caveats
    <<~EOS
      recruit launches Claude Code, which is installed separately:
        https://claude.com/claude-code
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/recruit --version")
    system bin/"recruit", "--lang", "en", "templates"
  end
end
