# Generated by scripts/release.sh in ronalove/recruit: change the script, not this file.
class Recruit < Formula
  desc "Launch teams of Claude Code agents in tmux, each knowing its role and teammates"
  homepage "https://github.com/ronalove/recruit"
  license "AGPL-3.0-or-later"

  head do
    url "https://github.com/ronalove/recruit.git", branch: "main"
    depends_on "rust" => :build
  end

  depends_on "tmux"

  on_macos do
    on_arm do
      url "https://github.com/ronalove/recruit/releases/download/v1.0.0/recruit-1.0.0-aarch64-apple-darwin.tar.gz"
      sha256 "73513baf87063d58a0ace68eb71304b085783140f59aeb8a1a87dcd0019cb6d0"
    end
    on_intel do
      url "https://github.com/ronalove/recruit/releases/download/v1.0.0/recruit-1.0.0-x86_64-apple-darwin.tar.gz"
      sha256 "c013737cf5ef444e75ef8f36237556b5bbc05a57a503625dc032030456576013"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ronalove/recruit/releases/download/v1.0.0/recruit-1.0.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "efb599628d73f25266f977b847c242ebbbc0abdd99421eb34969103a51477dd6"
    end
    on_intel do
      url "https://github.com/ronalove/recruit/releases/download/v1.0.0/recruit-1.0.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "bf55af1b8311dcf9210e946876932bd31fad55b0199bbbeb04f762c74ad0b8e2"
    end
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      bin.install "recruit"
    end
  end

  def caveats
    <<~EOS
      recruit launches Claude Code, which is installed separately:
        https://claude.com/claude-code
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/recruit --version")
    system bin/"recruit", "--lang", "en", "templates"
  end
end
