# Generated by scripts/release.sh in ronalove/recruit: change the script, not this file.
class Recruit < Formula
  desc "Launch teams of Claude Code agents in tmux, each knowing its role and teammates"
  homepage "https://github.com/ronalove/recruit"
  license "AGPL-3.0-or-later"

  head do
    url "https://github.com/ronalove/recruit.git", branch: "main"
    depends_on "rust" => :build
  end

  depends_on "tmux"

  on_macos do
    on_arm do
      url "https://github.com/ronalove/recruit/releases/download/v1.1.2/recruit-1.1.2-aarch64-apple-darwin.tar.gz"
      sha256 "896255e7271de97cb8ba242296ad3b5d83e30f33a508bc1b934488c700578f1f"
    end
    on_intel do
      url "https://github.com/ronalove/recruit/releases/download/v1.1.2/recruit-1.1.2-x86_64-apple-darwin.tar.gz"
      sha256 "b8a00f9a1047c03a1dea0085f2557593b8dacf1920c3f19987f0dec12603df7d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ronalove/recruit/releases/download/v1.1.2/recruit-1.1.2-aarch64-unknown-linux-musl.tar.gz"
      sha256 "c1c79d856729f7fa49fe4f3de4ff440ce0a0f1f1f84d98360b88a7d9464a1743"
    end
    on_intel do
      url "https://github.com/ronalove/recruit/releases/download/v1.1.2/recruit-1.1.2-x86_64-unknown-linux-musl.tar.gz"
      sha256 "6e268eb16f4d6065fd1facd6ad6321d82fac41312588876d324bd13271a3a31c"
    end
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      bin.install "recruit"
    end
  end

  def caveats
    <<~EOS
      recruit launches Claude Code, which is installed separately:
        https://claude.com/claude-code
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/recruit --version")
    system bin/"recruit", "--lang", "en", "templates"
  end
end
